$ErrorActionPreference = 'Stop'
$root = $PSScriptRoot
$cat = Get-Content -Raw "$root\catalog.json" | ConvertFrom-Json

$ids = [System.Collections.Generic.HashSet[string]]::new()
function Add-Ids($arr) { foreach ($x in $arr) { if ($null -ne $x) { [void]$ids.Add([string]$x) } } }

# hair: Male/Female -> ethnicity -> ids
foreach ($g in 'Male', 'Female') { foreach ($e in $cat.hair.$g.PSObject.Properties) { Add-Ids $e.Value } }
# faces: bucket -> ids
foreach ($b in $cat.faceBuckets.PSObject.Properties) { Add-Ids $b.Value }
# accessories: slot -> [[id, gender], ...]
foreach ($slot in $cat.accessorySlots.PSObject.Properties) {
    if ($slot.Value -is [System.Array] -and $slot.Value.Count -gt 0 -and $slot.Value[0] -is [System.Array]) {
        foreach ($entry in $slot.Value) { Add-Ids $entry[0] }
    }
}
# uniforms: shirt + pants
foreach ($g in 'Student_Male', 'Student_Female') {
    foreach ($u in $cat.uniforms.$g) { Add-Ids $u.shirt; Add-Ids $u.pants }
}

$list = @($ids)
$thumbs = @{}
$failed = [System.Collections.Generic.List[string]]::new()

for ($i = 0; $i -lt $list.Count; $i += 100) {
    $end = [Math]::Min($i + 99, $list.Count - 1)
    $chunk = $list[$i..$end]
    $url = "https://thumbnails.roblox.com/v1/assets?assetIds=$($chunk -join ',')&size=420x420&format=Png&isCircular=false"
    try {
        $resp = Invoke-RestMethod -Uri $url -TimeoutSec 30
        foreach ($d in $resp.data) {
            if ($d.state -eq 'Completed' -and $d.imageUrl) { $thumbs[[string]$d.targetId] = $d.imageUrl }
            else { $failed.Add([string]$d.targetId) }
        }
    } catch {
        Write-Host "chunk $i failed: $_"
        foreach ($id in $chunk) { $failed.Add([string]$id) }
    }
    Start-Sleep -Milliseconds 150
}

$js = "// generated by resolve_thumbs.ps1 - do not edit`n" +
      "const GACHA_DATA = " + (Get-Content -Raw "$root\catalog.json").Trim() + ";`n" +
      "const THUMBS = " + ($thumbs | ConvertTo-Json -Compress) + ";`n"
[System.IO.File]::WriteAllText("$root\gacha_data.js", $js, [System.Text.UTF8Encoding]::new($false))

Write-Host "total=$($list.Count) ok=$($thumbs.Count) failed=$($failed.Count)"
if ($failed.Count -gt 0) { Write-Host ("failed ids: " + ($failed -join ',')) }
